# Generated by Django 5.1.3 on 2024-11-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.TextField(default='FALSE'),
        ),
    ]
